#! /usr/bin/env bash


dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$dir"

set -eu

export TIMEOUT_ACTION="WAIT_STARTED"
if orderly -check-delay 60 -max-start-tokens 1 -start-tokens-per-second 0 -- \
  -name sv -all-commands ./sv -wait-started-timeout 2 > test1.out
then
  echo "expected failure"
  exit 1
fi

diff -u <(grep "^sv" test1.out) expected/wait-started.txt


export TIMEOUT_ACTION="CHECK"
if orderly -check-delay 60 -max-start-tokens 1 -start-tokens-per-second 0 -- \
  -name sv -all-commands ./sv -check-timeout 2  > test2.out
then
  echo "expected failure"
  exit 1
fi

diff -u <(grep "^sv" test2.out) expected/check.txt


export TIMEOUT_ACTION="CLEANUP"
if orderly -check-delay 60 -max-start-tokens 1 -start-tokens-per-second 0 -- \
  -name sv -all-commands ./sv -cleanup-timeout 2  > test3.out
then
  echo "expected failure"
  exit 1
fi

# This test has a slightly strange expected result.
# First the initial cleanup fails causing a shutdown,
# next the shutdown fails, causing a kill,
# finally the kill fails, and we exit anyway.
diff -u <(grep "^sv" test3.out) expected/cleanup.txt


export TIMEOUT_ACTION="SHUTDOWN"
orderly -check-delay 60 -max-start-tokens 1 -start-tokens-per-second 0 -- \
  -name sv -all-commands ./sv -shutdown-timeout 2 > test4.out &

pid="$!"
sleep 1
kill -SIGINT "$pid"
wait

diff -u <(grep "^sv" test4.out) expected/shutdown.txt

export SHUTDOWN_NOOP="yes"
export TIMEOUT_ACTION="SHUTDOWN"
orderly -check-delay 60 -max-start-tokens 1 -start-tokens-per-second 0 -- \
  -name sv -all-commands ./sv -shutdown-timeout 2 > test5.out &

pid="$!"
sleep 1
kill -SIGINT "$pid"
wait

diff -u <(grep "^sv" test5.out) expected/shutdown-noop.txt
